### ISSUE TITLE
Forgetting to `git submodule update --init` causes uncomprehensible panic in build script

### ISSUE THREAD

**Issue by oli-obk** [stainless-steel/mpg123-sys#1]
I think it should emit an error suggestion to run the submodule init if the `source` directory is empty or nonexistent.

**Comment by IvanUkhov** [comment]
Thanks for the issue! The `source` directory is a part of the Cargo package. So it doesn’t have to be checked out separately. Of course, if one wants to do some development and clones this repository without `--recursive`, there might be some issues, but it’s already a different story and has nothing to do with the build script.
