### ISSUE TITLE
mpg123_enc_enum consists of bitflags, but is represented by an enum

### ISSUE THREAD

**Issue by oli-obk** [stainless-steel/mpg123-sys#2]
The enum should be using `bitflags` instead. Every use case of the enum variants requires casting them to a `c_int`, the enum is never actually used to check for exhaustiveness (which isn't possible anyway, due to the bitflags nature of it)

This was found while analyzing the blockers for https://github.com/rust-lang/rust/pull/45002 (miri integration in const evaluatior). It is the last blocker on crates.io

**Comment by IvanUkhov** [comment]
Thanks! Fixed.

**Comment by oli-obk** [comment]
Thanks so much!
